### ISSUE TITLE
Cant connect with 943

### ISSUE THREAD

**Issue by jlruizmlg** [macexx/openvpn-as#1]
Hello, i try to use your container, i can't connect through 943 port

the logs say you are using 9443 
"
*\* Running /etc/my_init.d/00_config.sh...
Copying configuration from install directory to host!
Checking configuration, Setting Openvpn-AS defaults or update is beeing made!
MOD Default {u'auth.module.type': u'pam'} {u'auth.module.type': 'local'}
MOD Default {u'vpn.daemon.0.listen.port': u'443'} {u'vpn.daemon.0.listen.port': '9443'}
MOD Default {u'vpn.server.daemon.tcp.port': u'443'} {u'vpn.server.daemon.tcp.port': '9443'}
Interface variable is not set, Defaulting to interface eth0!
"

when change the porto to 9443 and https works, maybe something wrong in the documentation?

thanks.

**Comment by macexx** [comment]
Sorry for the late replay, are you taking about connecting to the wegui or openvpn with tcp connection?

port 943 is webui (https)
port 9443 is openvpn tcp connection (will also server webui if not turned off in webui settings)

All the can be changed in the openvpn web ui.
